version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  app:
    build: ./app
    container_name: app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
